USE [master]
GO

/****** Object:  Database [MFM_Financial]    Script Date: 11/3/2019 2:31:45 PM ******/
CREATE DATABASE [MFM_Financial]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MFM_Financial', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\MFM_Financial.mdf' , SIZE = 139264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MFM_Financial_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\MFM_Financial_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MFM_Financial].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MFM_Financial] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MFM_Financial] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MFM_Financial] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MFM_Financial] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MFM_Financial] SET ARITHABORT OFF 
GO

ALTER DATABASE [MFM_Financial] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MFM_Financial] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MFM_Financial] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MFM_Financial] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MFM_Financial] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MFM_Financial] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MFM_Financial] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MFM_Financial] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MFM_Financial] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MFM_Financial] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MFM_Financial] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MFM_Financial] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MFM_Financial] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MFM_Financial] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MFM_Financial] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MFM_Financial] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MFM_Financial] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MFM_Financial] SET RECOVERY FULL 
GO

ALTER DATABASE [MFM_Financial] SET  MULTI_USER 
GO

ALTER DATABASE [MFM_Financial] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MFM_Financial] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MFM_Financial] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MFM_Financial] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MFM_Financial] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MFM_Financial] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MFM_Financial] SET  READ_WRITE 
GO




USE [MFM_Financial]
GO

/****** Object:  Schema [FinData]    Script Date: 11/3/2019 2:32:41 PM ******/
CREATE SCHEMA [FinData]
GO

USE [MFM_Financial]
GO

/****** Object:  Table [FinData].[HistPrice]    Script Date: 11/3/2019 2:36:03 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [FinData].[HistPrice](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[InstID] [int] NOT NULL,
	[Date] [date] NULL,
	[OpenPrice] [float] NULL,
	[HighPrice] [float] NULL,
	[LowPrice] [float] NULL,
	[ClosePrice] [float] NULL,
	[Volume] [bigint] NULL,
	[AdjClosePrice] [float] NULL,
 CONSTRAINT [PK_HistPrice] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [FinData].[HistPrice]  WITH CHECK ADD  CONSTRAINT [FK_HistPrice_Instrument] FOREIGN KEY([InstID])
REFERENCES [FinData].[Instrument] ([ID])
GO

ALTER TABLE [FinData].[HistPrice] CHECK CONSTRAINT [FK_HistPrice_Instrument]
GO



USE [MFM_Financial]
GO

/****** Object:  Table [FinData].[Instrument]    Script Date: 11/3/2019 2:37:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [FinData].[Instrument](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CompanyName] [varchar](250) NULL,
	[StockTicker] [varchar](10) NULL,
	[Market] [varchar](10) NULL,
	[Sector] [varchar](100) NULL,
 CONSTRAINT [PK_Instrument] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

